//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessPassMaster
    {
        public int APID { get; set; }
        public Nullable<int> CompID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<decimal> AccessPassID { get; set; }
        public Nullable<System.DateTime> SwipeDate { get; set; }
        public Nullable<System.DateTime> SwipeTime { get; set; }
        public string DoorID { get; set; }
    }
}
