//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessTran
    {
        public int BATranID { get; set; }
        public Nullable<int> BAID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
