//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessMaster
    {
        public int BAID { get; set; }
        public Nullable<int> DataCenter { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> StDateTime { get; set; }
        public Nullable<System.TimeSpan> StTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> phone { get; set; }
        public string SFirstName { get; set; }
        public string SLastName { get; set; }
        public string SCompany { get; set; }
        public Nullable<decimal> SPhone { get; set; }
        public string TFirstName { get; set; }
        public string TLastName { get; set; }
        public string TCompany { get; set; }
        public Nullable<decimal> TPhone { get; set; }
        public string FFirstName { get; set; }
        public string FLastName { get; set; }
        public string FCompany { get; set; }
        public Nullable<decimal> FPhone { get; set; }
        public Nullable<int> TicketID { get; set; }
        public string Prefix { get; set; }
    }
}
