//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryMaster
    {
        public int BDID { get; set; }
        public Nullable<int> DataCenter { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> StDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<decimal> Boxes { get; set; }
        public string TrackingNo { get; set; }
        public string ProjectRef { get; set; }
        public Nullable<bool> Storage { get; set; }
        public Nullable<bool> RemoteHands { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> TicketID { get; set; }
        public string Prefix { get; set; }
    }
}
